/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MapRouteImport } from './routes/_map'
import { Route as MapIndexRouteImport } from './routes/_map/index'
import { Route as MapHRouteImport } from './routes/_map/h'
import { Route as MapRIdRouteImport } from './routes/_map/r.$id'
import { Route as MapHIdRouteImport } from './routes/_map/h.$id'

const MapRoute = MapRouteImport.update({
  id: '/_map',
  getParentRoute: () => rootRouteImport,
} as any)
const MapIndexRoute = MapIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MapRoute,
} as any)
const MapHRoute = MapHRouteImport.update({
  id: '/h',
  path: '/h',
  getParentRoute: () => MapRoute,
} as any)
const MapRIdRoute = MapRIdRouteImport.update({
  id: '/r/$id',
  path: '/r/$id',
  getParentRoute: () => MapRoute,
} as any)
const MapHIdRoute = MapHIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => MapHRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof MapIndexRoute
  '/h': typeof MapHRouteWithChildren
  '/h/$id': typeof MapHIdRoute
  '/r/$id': typeof MapRIdRoute
}
export interface FileRoutesByTo {
  '/h': typeof MapHRouteWithChildren
  '/': typeof MapIndexRoute
  '/h/$id': typeof MapHIdRoute
  '/r/$id': typeof MapRIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_map': typeof MapRouteWithChildren
  '/_map/h': typeof MapHRouteWithChildren
  '/_map/': typeof MapIndexRoute
  '/_map/h/$id': typeof MapHIdRoute
  '/_map/r/$id': typeof MapRIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/h' | '/h/$id' | '/r/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/h' | '/' | '/h/$id' | '/r/$id'
  id:
    | '__root__'
    | '/_map'
    | '/_map/h'
    | '/_map/'
    | '/_map/h/$id'
    | '/_map/r/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  MapRoute: typeof MapRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_map': {
      id: '/_map'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof MapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_map/': {
      id: '/_map/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof MapIndexRouteImport
      parentRoute: typeof MapRoute
    }
    '/_map/h': {
      id: '/_map/h'
      path: '/h'
      fullPath: '/h'
      preLoaderRoute: typeof MapHRouteImport
      parentRoute: typeof MapRoute
    }
    '/_map/r/$id': {
      id: '/_map/r/$id'
      path: '/r/$id'
      fullPath: '/r/$id'
      preLoaderRoute: typeof MapRIdRouteImport
      parentRoute: typeof MapRoute
    }
    '/_map/h/$id': {
      id: '/_map/h/$id'
      path: '/$id'
      fullPath: '/h/$id'
      preLoaderRoute: typeof MapHIdRouteImport
      parentRoute: typeof MapHRoute
    }
  }
}

interface MapHRouteChildren {
  MapHIdRoute: typeof MapHIdRoute
}

const MapHRouteChildren: MapHRouteChildren = {
  MapHIdRoute: MapHIdRoute,
}

const MapHRouteWithChildren = MapHRoute._addFileChildren(MapHRouteChildren)

interface MapRouteChildren {
  MapHRoute: typeof MapHRouteWithChildren
  MapIndexRoute: typeof MapIndexRoute
  MapRIdRoute: typeof MapRIdRoute
}

const MapRouteChildren: MapRouteChildren = {
  MapHRoute: MapHRouteWithChildren,
  MapIndexRoute: MapIndexRoute,
  MapRIdRoute: MapRIdRoute,
}

const MapRouteWithChildren = MapRoute._addFileChildren(MapRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  MapRoute: MapRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
